### ISSUE TITLE
If Command editing when select Web Element Exists

### ISSUE THREAD

**Issue by msshubin** [saucepleez/tasktServer#9]
Hi, Jason. I found strange things.
1. Add to script Begin If Command and select "Web Element Exists", then select By ID
![image](https://user-images.githubusercontent.com/22539710/51591429-62d67f00-1f06-11e9-9dd8-644e9953a6c6.png)
2. Click Ok,
3. Then i want no change "Element Search Method" to "Find Element By CSS Selector", but when i open this comman for edit, i can't find combobox - there are only text string:
![image](https://user-images.githubusercontent.com/22539710/51591518-a29d6680-1f06-11e9-960b-5565f7d3eb7a.png)

**Comment by saucepleez** [comment]
@msshubin  You have posted this issue in the wrong repository (this is for the server component).  I will take a look and address accordingly -- This behavior is being caused by the Selection Change not being fired (ex. The If Command Type box must be updated for the list to populate,  I will look at remediation.

**Comment by saucepleez** [comment]
This has been addressed for v.2.5.0.0
